spring:
  application:
    name: flight-booking-service
  datasource:
    url: jdbc:h2:mem:flight-booking-db
    username: username
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log:
      classpath:db/changelog/db.changelog-master.xml

business:
  maxDaysFromToday: 30
  maxPassengersPerFlight: 50
  maxPassengersPerBooking: 7
